[pytest]
testpaths = tests

# Global test options
addopts = -v -ra --reruns 1 --reruns-delay 2

markers =
    api: API tests
    smoke: basic functionality tests
    regression: full test coverage
    workflow: end-to-end workflow tests
    performance: response time tests
    ui: UI tests
    flaky: tests that may be rerun on failure
